# Generated by Django 5.1.5 on 2025-02-28 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_invitation_joinrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project name', max_length=200)),
                ('summary', models.TextField(help_text='Brief description of the project')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='project_covers/')),
                ('github_link', models.URLField(blank=True, help_text='GitHub repository URL')),
                ('live_demo', models.URLField(blank=True, help_text='Live website URL (if available)', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.userprofile')),
            ],
        ),
    ]
